export default function Head() {
  return (
    <>
      <title>Bubbletic</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" type="image/png" href="/images/favicon-32x32.png" />
    </>
  );
}
